# Creation

In [2]:
#importing module
import numpy as np

In [4]:
#creating 1D array
array1 = np.array([1,2,3])


In [5]:
#returning the datatype of the array
array1.dtype

dtype('int32')

In [10]:
#
matrix = np.array([np.arange(3), [i for i in range(1,4)], [6,7,8]])
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


# Initialization

In [11]:
#define an array of zeros having the datatype float
np.zeros((5,2,2), dtype=float)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [13]:
#define an array full of ones
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#creating an array of 3x4 matrix
#having random data
np.empty([3,4])

array([[1.35404729e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.37923634e-057, 6.22689154e-038,
        6.12880744e-062],
       [1.68921941e+160, 4.66458786e-062, 9.41555856e-067,
        1.05931512e+165]])

In [20]:
#arrange with evenly spaced values
np.arange(2,10,2)
#np.arange(start_val, end_val, period)

array([2, 4, 6, 8])

In [23]:
#rearrangeing the size of the array
np.arange(2,10,1).reshape(4,2)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
#creating an array with constants 2x3 matrix including the value 4
np.full([2,3], 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [26]:
#identity matrix created 3x3
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#creating an array 5 splits from 2 to 3 including those values
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

# Copying, Sorting, Shifting

In [29]:
#Return the copy of the defined matrix called matrix
np.copy(matrix)

array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [30]:
#matrix deep copy function
matrix.copy()

array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [31]:
#shallow copy 
matrix.view()

array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [33]:
#sorting values in assending order
matrix.sort()
print(matrix)

[[0 1 2]
 [1 2 3]
 [6 7 8]]


In [38]:
#sort values along the specified axis
matrix.sort(axis=0)

In [39]:
matrix.sort(axis=1)

In [42]:
mat = np.array( [[1,2,3], [3,4,5], [7,4,2], [9,6,4]])
print(mat)

[[1 2 3]
 [3 4 5]
 [7 4 2]
 [9 6 4]]


In [46]:
#values are sorted along the column wise
mat.sort(axis=0)
mat

array([[1, 2, 2],
       [3, 4, 3],
       [7, 4, 4],
       [9, 6, 5]])

In [48]:
#values are sorting along the row
mat.sort(axis=1)
mat

array([[1, 2, 2],
       [3, 3, 4],
       [4, 4, 7],
       [5, 6, 9]])

In [50]:
#indexing starting from 0 
matrix[0:,:1]

array([[0],
       [1],
       [6]])

In [51]:
matrix

array([[0, 1, 2],
       [1, 2, 3],
       [6, 7, 8]])

In [53]:
matrix[:1, :]

array([[0, 1, 2]])

In [55]:
matrix[:2, 0:2]

array([[0, 1],
       [1, 2]])

In [58]:
matrix[:1, :]

array([[0, 1, 2]])

# Try Out

In [59]:
#change the specific value in the array
matrix[0,0] = 45
matrix

array([[45,  1,  2],
       [ 1,  2,  3],
       [ 6,  7,  8]])

In [61]:
#print the 1st raw first value
matrix[0,0]

45

In [64]:
#making changes to all the values in the first raw
matrix[0] = 42
matrix

array([[42, 42, 42],
       [ 1,  2,  3],
       [ 6,  7,  8]])

In [65]:
#interpret all the values from the 1st raw
matrix[1:]

array([[1, 2, 3],
       [6, 7, 8]])

In [69]:
#show values 
matrix[0:2]

array([[42, 42, 42],
       [ 1,  2,  3]])

In [70]:
matrix[:]

array([[42, 42, 42],
       [ 1,  2,  3],
       [ 6,  7,  8]])

In [71]:
matrix[:1, :2]

array([[42, 42]])

In [73]:
matrix[1: , 1:]

array([[2, 3],
       [7, 8]])

In [74]:
matrix[:2, 1:]

array([[42, 42],
       [ 2,  3]])

In [75]:
#using for flatten the arrays like 2 dimetional and multi dimentional
matrix.ravel()

array([42, 42, 42,  1,  2,  3,  6,  7,  8])

In [76]:
matrix[:, 1].copy()


array([42,  2,  7])

In [78]:
matrix[0].tolist()

[42, 42, 42]

In [82]:
matrix.reshape(9)

array([42, 42, 42,  1,  2,  3,  6,  7,  8])

In [9]:
#matrix multiplication
matA = np.array([[2,4,7],[5,3,9], [2,1,7]])
matB = np.random.randint(-3,3,(3,7))

In [11]:
matC = np.matmul(matA, matB)
matC

array([[-24,  -9, -13, -29,  22,   2, -20],
       [-22, -11, -14, -26,  24,   9, -33],
       [-15, -15, -16, -20,  16,  11, -20]])

In [14]:
import time
start_time = time.time()
matD = np.matmul(matA, matB)
end_time = time.time()
duration = start_time-end_time

print('Duration =', duration)

Duration = -0.0010030269622802734


In [18]:
print(matD)

[[-24  -9 -13 -29  22   2 -20]
 [-22 -11 -14 -26  24   9 -33]
 [-15 -15 -16 -20  16  11 -20]]


# Pandas

In [21]:
#import pandas library
import pandas as pd

In [23]:
#creating pandas dictionaries using series
a = pd.Series([1,4,-2,'string'], index=['a','b','c','d'])
a

a         1
b         4
c        -2
d    string
dtype: object

In [27]:
#creating a dataframe using pandas
data = {'polulation' : [12,24,56,234,78,12], 'animals': ['dog', 'cat', 'wold', 'parrot', 'fox', 'snake']}
data
#passing the dataset to the dataframe
df = pd.DataFrame(data, index=[1,2,3,4,5,6])
df

polulation animals
1          12     dog
2          24     cat
3          56    wold
4         234  parrot
5          78     fox
6          12   snake

In [30]:
dataset = pd.read_csv('Dataset/sampleDataset.csv')
dataset

A         B         C         D         E         F     G            H  \
0   5.1  0.222222  3.500000  0.625000  1.400000  0.067797  0.20  0.041666667   
1   4.9  0.166667  3.000000  0.416667  1.400000  0.067797  0.20  0.041666667   
2   4.7  0.111111  3.200000  0.500000  1.300000       NaN  0.20  0.041666667   
3   4.6  0.083333  3.100000  0.458333  1.500000  0.084746  0.20  0.041666667   
4   NaN  0.194444  3.600000  0.666667  1.400000       NaN  0.20  0.041666667   
..  ...       ...       ...       ...       ...       ...   ...          ...   
95  7.2  0.805556  3.000000  0.416667  5.800000  0.813559  1.60        0.625   
96  7.4       NaN  0.333333  6.100000  0.864407  1.900000  0.75    virginica   
97  7.9  0.999900  3.800000  0.750000  6.400000  0.915254  2.00  0.791666667   
98  6.4  0.583333  2.800000  0.333333  5.600000  0.779661  2.20        0.875   
99  6.3  0.555556  2.800000  0.333333  5.100000  0.694915  1.50  0.583333333   

            I  
0      setosa  
1      setosa  
2      setosa  
3      setosa  
4      setosa  
..        ...  
95  virginica  
96        NaN  
97  virginica  
98  virginica  
99  virginica  

[100 rows x 9 columns]

In [33]:
dataset.isnull()

A      B      C      D      E      F      G      H      I
0   False  False  False  False  False  False  False  False  False
1   False  False  False  False  False  False  False  False  False
2   False  False  False  False  False   True  False  False  False
3   False  False  False  False  False  False  False  False  False
4    True  False  False  False  False   True  False  False  False
..    ...    ...    ...    ...    ...    ...    ...    ...    ...
95  False  False  False  False  False  False  False  False  False
96  False   True  False  False  False  False  False  False   True
97  False  False  False  False  False  False  False  False  False
98  False  False  False  False  False  False  False  False  False
99  False  False  False  False  False  False  False  False  False

[100 rows x 9 columns]