### OHE in text -> vectors conversion

In [1]:
import numpy as np

# Sample list of sentences
sentences = [
    "The quick brown fox jumps over the lazy dog",
    "A quick brown fox is sleeping on the couch",
    "The lazy dog is barking at the fox"
]

# Step 1: Tokenize and find the vocabulary
vocabulary = set()
for sentence in sentences:
    words = sentence.split()
    for word in words:
        vocabulary.add(word)

# Convert the vocabulary to a sorted list
vocabulary = sorted(vocabulary)
vocab_size = len(vocabulary)

# Step 2: Create a dictionary to map each word to its index
word_to_index = {word: idx for idx, word in enumerate(vocabulary)}

# Step 3: Apply One-Hot Encoding
one_hot_encoded_sentences = []
for sentence in sentences:
    encoded_sentence = np.zeros(vocab_size)
    words = sentence.split()
    for word in words:
        if word in word_to_index:
            encoded_sentence[word_to_index[word]] = 1
    one_hot_encoded_sentences.append(encoded_sentence)

# Print the results
print("Vocabulary:", vocabulary)
for i, encoded_sentence in enumerate(one_hot_encoded_sentences):
    print(f"Sentence {i + 1}:\n{encoded_sentence}\n")

Vocabulary: ['A', 'The', 'at', 'barking', 'brown', 'couch', 'dog', 'fox', 'is', 'jumps', 'lazy', 'on', 'over', 'quick', 'sleeping', 'the']
Sentence 1:
[0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]

Sentence 2:
[1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1.]

Sentence 3:
[0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1.]





This code will output the vocabulary and the One-Hot Encoded representation of each sentence.
